<a href="https://colab.research.google.com/github/varuchoterminator/Hola_Mundo/blob/main/Actividad1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importamos librerias requeridas 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivos csv desde seaborn
df=sns.load_dataset(name='car_crashes')

In [ ]:
#imprimimos las primeras filas o registros del Dataframe
df.head(5)

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [ ]:
#imprimimos las ultimas filas o registros del Dataframe
df.tail(5)

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY

In [ ]:
df.info

In [ ]:
#cargar archivo csv desde equipo 
from google.colab import files
files.upload()

Saving car_crashes.csv to car_crashes.csv

{'car_crashes.csv': b'total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev\r\n18.8,7.332000000000001,5.64,18.048000000000002,15.04,784.55,145.08,AL\r\n18.1,7.421,4.525,16.290000000000003,17.014,1053.48,133.93,AK\r\n18.6,6.51,5.208000000000001,15.624,17.856,899.47,110.35,AZ\r\n22.4,4.032,5.824,21.055999999999997,21.28,827.34,142.39,AR\r\n12.0,4.2,3.36,10.92,10.68,878.41,165.63,CA\r\n13.6,5.032,3.8080000000000003,10.743999999999998,12.92,835.5,139.91,CO\r\n10.8,4.968,3.888,9.396,8.856,1068.73,167.02,CT\r\n16.2,6.156000000000001,4.86,14.094,16.038,1137.87,151.48,DE\r\n5.9,2.0060000000000002,1.5930000000000002,5.9,5.9,1273.89,136.05,DC\r\n17.9,3.759,5.190999999999999,16.468,16.826,1160.13,144.18,FL\r\n15.6,2.964,3.9,14.82,14.508,913.15,142.8,GA\r\n17.5,9.45,7.175,14.35,15.225,861.18,120.92,HI\r\n15.3,5.508000000000001,4.437,13.005,14.994000000000002,641.96,82.75,ID\r\n12.8,4.6080000000000005,4.352,12.032,12.288000000000002,803.11,139.15,IL\r\n14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN\r\n15.7,2.6689999999999996,3.925,15.229,13.658999999999999,649.06,114.47,IA\r\n17.8,4.806,4.272,13.706000000000001,15.13,780.45,133.8,KS\r\n21.4,4.066,4.922,16.691999999999997,16.264,872.51,137.13,KY\r\n20.5,7.175,6.765,14.965,20.09,1281.55,194.78,LA\r\n15.1,5.7379999999999995,4.53,13.137,12.684,661.88,96.57,ME\r\n12.5,4.25,4.0,8.875,12.375,1048.78,192.7,MD\r\n8.2,1.886,2.87,7.1339999999999995,6.56,1011.14,135.63,MA\r\n14.1,3.384,3.948,13.395,10.857000000000001,1110.61,152.26,MI\r\n9.6,2.2079999999999997,2.784,8.448,8.448,777.18,133.35,MN\r\n17.6,2.64,5.456,1.76,17.6,896.07,155.77,MS\r\n16.1,6.923000000000001,5.474000000000001,14.812000000000001,13.524000000000001,790.32,144.45,MO\r\n21.4,8.345999999999998,9.415999999999999,17.976,18.189999999999998,816.21,85.15,MT\r\n14.9,1.9370000000000003,5.215,13.857000000000001,13.41,732.28,114.82,NE\r\n14.7,5.439,4.704,13.965,14.552999999999999,1029.87,138.71,NV\r\n11.6,4.06,3.48,10.091999999999999,9.628,746.54,120.21,NH\r\n11.2,1.7919999999999998,3.1359999999999997,9.632,8.735999999999999,1301.52,159.85,NJ\r\n18.4,3.4959999999999996,4.968,12.328,18.031999999999996,869.85,120.75,NM\r\n12.3,3.9360000000000004,3.5670000000000006,10.824000000000002,9.84,1234.31,150.01,NY\r\n16.8,6.5520000000000005,5.208000000000001,15.792,13.607999999999999,708.24,127.82,NC\r\n23.9,5.496999999999999,10.038,23.660999999999998,20.554000000000002,688.75,109.72,ND\r\n14.1,3.948,4.794,13.958999999999998,11.562000000000001,697.73,133.52,OH\r\n19.9,6.367999999999999,5.770999999999999,18.308,18.706,881.51,178.86,OK\r\n12.8,4.224,3.3280000000000003,8.576,11.52,804.71,104.61,OR\r\n18.2,9.1,5.6419999999999995,17.471999999999998,16.016,905.99,153.86,PA\r\n11.1,3.7739999999999996,4.218,10.212,8.769,1148.99,148.58,RI\r\n23.9,9.081999999999999,9.799,22.943999999999996,19.358999999999998,858.97,116.29,SC\r\n19.4,6.013999999999999,6.401999999999999,19.011999999999997,16.683999999999997,669.31,96.87,SD\r\n19.5,4.095,5.655,15.99,15.795,767.91,155.57,TN\r\n19.4,7.76,7.371999999999999,17.654,16.878,1004.75,156.83,TX\r\n11.3,4.859,1.808,9.944,10.848000000000003,809.38,109.48,UT\r\n13.6,4.08,4.08,13.056,12.92,716.2,109.61,VT\r\n12.7,2.413,3.429,11.049,11.175999999999998,768.95,153.72,VA\r\n10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA\r\n23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV\r\n13.8,4.968,4.554,5.382000000000001,11.592,670.31,106.62,WI\r\n17.4,7.308,5.568,14.094,15.659999999999998,791.14,122.04,WY\r\n'}

In [ ]:
#convertir en dataframe
df=pd.read_csv("car_crashes.csv")
df

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA
5,13.6,5.032,3.808,10.744,12.920,835.50,139.91,CO
6,10.8,4.968,3.888,9.396,8.856,1068.73,167.02,CT
7,16.2,6.156,4.860,14.094,16.038,1137.87,151.48,DE
8,5.9,2.006,1.593,5.900,5.900,1273.89,136.05,DC
9,17.9,3.759,5.191,16.468,16.826,1160.13,144.18,FL
10,15.6,2.964,3.900,14.820,14.508,913.15,142.80,GA
11,17.5,9.450,7.175,14.350,15.225,861.18,120.92,HI
12,15.3,5.508,4.437,13.005,14.994,641.96,82.75,ID
13,12.8,4.608,4.352,12.032,12.288,803.11,139.15,IL
14,14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN
15,15.7,2.669,3.925,15.229,13.659,649.06,114.47,IA
16,17.8,4.806,4.272,13.706,15.130,780.45,133.80,KS
17,21.4,4.066,4.922,16.692,16.264,872.51,137.13,KY
18,20.5,7.175,6.765,14.965,20.090,1281.55,194.78,LA
19,15.1,5.738,4.530,13.137,12.684,661.88,96.57,ME
20,12.5,4.250,4.000,8.875,12.375,1048.78,192.70,MD
21,8.2,1.886,2.870,7.134,6.560,1011.14,135.63,MA
22,14.1,3.384,3.948,13.395,10.857,1110.61,152.26,MI
23,9.6,2.208,2.784,8.448,8.448,777.18,133.35,MN
24,17.6,2.640,5.456,1.760,17.600,896.07,155.77,MS
25,16.1,6.923,5.474,14.812,13.524,790.32,144.45,MO
26,21.4,8.346,9.416,17.976,18.190,816.21,85.15,MT
27,14.9,1.937,5.215,13.857,13.410,732.28,114.82,NE
28,14.7,5.439,4.704,13.965,14.553,1029.87,138.71,NV
29,11.6,4.060,3.480,10.092,9.628,746.54,120.21,NH
30,11.2,1.792,3.136,9.632,8.736,1301.52,159.85,NJ
31,18.4,3.496,4.968,12.328,18.032,869.85,120.75,NM
32,12.3,3.936,3.567,10.824,9.840,1234.31,150.01,NY
33,16.8,6.552,5.208,15.792,13.608,708.24,127.82,NC
34,23.9,5.497,10.038,23.661,20.554,688.75,109.72,ND
35,14.1,3.948,4.794,13.959,11.562,697.73,133.52,OH
36,19.9,6.368,5.771,18.308,18.706,881.51,178.86,OK
37,12.8,4.224,3.328,8.576,11.520,804.71,104.61,OR
38,18.2,9.100,5.642,17.472,16.016,905.99,153.86,PA
39,11.1,3.774,4.218,10.212,8.769,1148.99,148.58,RI
40,23.9,9.082,9.799,22.944,19.359,858.97,116.29,SC
41,19.4,6.014,6.402,19.012,16.684,669.31,96.87,SD
42,19.5,4.095,5.655,15.990,15.795,767.91,155.57,TN
43,19.4,7.760,7.372,17.654,16.878,1004.75,156.83,TX
44,11.3,4.859,1.808,9.944,10.848,809.38,109.48,UT
45,13.6,4.080,4.080,13.056,12.920,716.20,109.61,VT
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY

In [ ]:
#cargar archivo csv desde seaborn
df=sns.load_dataset(name'car_crashes)